# Generated by Django 3.2.6 on 2021-08-26 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Aluno', max_length=100)),
                ('cpf', models.CharField(default='', help_text='CPF do Aluno', max_length=12)),
                ('email', models.CharField(default='', help_text='e-mail', max_length=100)),
                ('data_nasc', models.DateField(blank=True, default='null', verbose_name='Data de Nascimento')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
