# Generated by Django 3.2.6 on 2021-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nasc',
            field=models.DateField(blank=True, default=' ', verbose_name='Data de Nascimento'),
        ),
    ]
