# Generated by Django 3.2.6 on 2021-08-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nasc',
            field=models.DateField(blank=True, default='', verbose_name='Data de Nascimento'),
        ),
    ]
