# Generated by Django 3.2.6 on 2021-08-30 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Core',
        ),
    ]
