# Generated by Django 3.2.6 on 2021-08-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(help_text='Nome do Professor', max_length=120),
        ),
    ]
