# Generated by Django 3.2.6 on 2021-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_professor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default='', help_text='CPF', max_length=12),
        ),
        migrations.AddField(
            model_name='professor',
            name='formacao',
            field=models.CharField(default='', help_text='Formação', max_length=200),
        ),
    ]
