# Generated by Django 3.2.6 on 2021-08-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20210828_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.CharField(default='', help_text='E-mail', max_length=100),
        ),
    ]
