# Generated by Django 3.2.6 on 2021-08-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0005_alter_professor_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
